# springboot 服务配置
# todo: 有些配置可以改成服务发现
server:
  # 端口
  port: 8080
  # 服务根路径
  servlet:
    context-path: /aurora/red/v1

  # 数据库 MySQL 配置
  datasource:
    url: jdbc:mysql://1.117.231.230:3306/spider?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=true
    username: shaopengwei
    password: Shao@1225
    driver-class-name: com.mysql.cj.jdbc.Driver